### ISSUE TITLE
Option to suppress output

### ISSUE THREAD

**Issue by laxman20** [mybuilder/kongfig#100]
Kongfig reveals api keys in its output when it runs. It would be nice if there was an option to suppress this without having to hide the entire output.

**Comment by tophercullen** [comment]
@CyExy Running into a similar use case as I integrate kongfig into our CI environment. I think the default behavior should not output api keys as part of the normal logs.

**Comment by CyExy** [comment]
Would this work for you? https://github.com/mybuilder/kongfig/pull/115

**Comment by tophercullen** [comment]
That actually looks like a great. :+1:

**Comment by CyExy** [comment]
Released now
