### ISSUE TITLE
Kongfig apply fails when paging required

### ISSUE THREAD

**Issue by sebastianroesch** [mybuilder/kongfig#105]
I apply my kongfig with the following command:
`kongfig apply --path config.yml --https --host my-host/admin --header apikey:some-key`

Here is the result:
```
Loading config config.yml
Apply config to my-host/admin
Kong version: 0.11.1
Error: http://localhost:8001/plugins?offset=EBc4d3Ri50C2sAkYIzguyOQWABRocS1jaGVjay1wZXJtaXNzaW9uc%2FB%2F%2F%2F%2Bb8H%2F%2F%2F%2F4%3D&size=100: 404 Not Found
 Error: http://localhost:8001/plugins?offset=EBc4d3Ri50C2sAkYIzguyOQWABRocS1jaGVjay1wZXJtaXNzaW9uc%2FB%2F%2F%2F%2Bb8H%2F%2F%2F%2F4%3D&size=100: 404 Not Found
    at /usr/local/lib/node_modules/kongfig/lib/adminApi.js:131:25
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

It seems as if kongfig would use `localhost:8001` when getting the remaining pages of an endpoint instead of the provided host argument.

**Comment by CyExy** [comment]
This is likely to be kong that is returning the wrong URL, I'll have a look.

**Comment by CyExy** [comment]
Please could you look at https://github.com/mybuilder/kongfig/pull/123 this PR should fix your issue

**Comment by sebastianroesch** [comment]
Thanks, my issue has been fixed in the meantime.
