### ISSUE TITLE
[kong 0.9.9] `kongfig dump > kongfig.yml` errors `upstreams: 404 Not Found`

### ISSUE THREAD

**Issue by millermatt** [mybuilder/kongfig#106]
Steps to reproduce:
```
git clone https://github.com/PGBI/kong-dashboard.git
cd kong-dashboard
KONG_VERSION=0.9.9 docker-compose up
```
Add an api & consumer, then run:
```
kongfig dump > kongfig.yml
```
This results in:
```
Error: http://localhost:8001/upstreams: 404 Not Found
 Error: http://localhost:8001/upstreams: 404 Not Found
    at /Users/millerm/repos/test-app/node_modules/kongfig/lib/adminApi.js:131:25
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
I have kongfig installed locally, so my actual dump command is `./node_modules/.bin/kongfig dump > kongfig.yml`

I wonder if the relatively recent PR to support upstreams broke compatibility with Kong 9x.

**Comment by millermatt** [comment]
My workaround is to uninstall `kongfig` and install `kongfig@1.3.0`

**Comment by CyExy** [comment]
Thanks for submitting the issue, `kongfig@1.4.1` now available. PS! maybe you can help me with this issue #103 ;)
