### ISSUE TITLE
Secured kong API gives 401 unauthorized

### ISSUE THREAD

**Issue by yvsssantosh** [mybuilder/kongfig#119]
Hi, 

I'm running kong on GKE (Google Kubernetes Engine) and I have it exposed using a load balancer. Now that I don't want others to mess up my configuration I've added a basic auth using kong itself using username and password. Now I've made a lot of changes in the staging server which I'd like to copy to the production server. 
When I'm using kongfig, I get

![screen shot 2018-02-19 at 6 23 33 pm](https://user-images.githubusercontent.com/11535830/36378761-1eb20718-15a2-11e8-849d-9b82e6e41a7c.png)

I'm using the command
```
$ kongfig dump -f json --host my-kong-host.com > dumps.json
```
Please let me know if there is any option to pass credentials.

**Comment by CyExy** [comment]
Should be able to use the `—header` option

**Comment by CyExy** [comment]
`--header 'Authorization: ...'` should do the trick so closing it now, please re-open if you still having issues.
