### ISSUE TITLE
dump error with kong 0.12.1

### ISSUE THREAD

**Issue by wjeanneau** [mybuilder/kongfig#120]
**Is this a BUG REPORT or FEATURE REQUEST?**
BUG REPORT

**Version of kong and kongfig:**
kong: 0.12.1
kongfig: 1.4.2

**What happened:**
The _dump_ command seems to be broken with those versions.

`# kongfig dump --host localhost:8001
Error: http://localhost:8001/upstreams/74d6359b-ed58-4198-9e1b-a441341948c2/targets/active/: 405 Not Allowed
 Error: http://localhost:8001/upstreams/74d6359b-ed58-4198-9e1b-a441341948c2/targets/active/: 405 Not Allowed
    at /usr/lib/node_modules/kongfig/lib/adminApi.js:133:25
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)`

**Anything else we need to know:**
It looks like version greater than 0.12.0 are supported, but according to the error I got, it appears that the program is sill using the function _fetchTargetsV11Active_
https://github.com/mybuilder/kongfig/blob/76a27e716bac19ea55cd9270ce956fc37e701851/src/kongState.js#L73

**Comment by CyExy** [comment]
`kongfig@1.5.0` should fix this issue

**Comment by wjeanneau** [comment]
My tests are passing. I'll let you know if i see something else.
Thank you for your work !
