### ISSUE TITLE
upstreams.map is not a function error when passing jwt header

### ISSUE THREAD

**Issue by mburket** [mybuilder/kongfig#122]
Hi, 

I am trying to secure my admin apis with jwt token. When I post to the kongfig i receive error. I wonder if it can't parse the "Bearer jwt" correctly since it has a space between "Bearer" and the token?

Here is an example of my command: kongfig apply --path file-name --https --host admin-url --header 'Authorization: Bearer jwt'  

Here is the error i get: Kong version: 0.12.1
TypeError: upstreams.map is not a function
 TypeError: upstreams.map is not a function
    at _callee2$ (/usr/local/lib/node_modules/kongfig/lib/kongState.js:47:54)
    at tryCatch (/usr/local/lib/node_modules/kongfig/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/usr/local/lib/node_modules/kongfig/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/kongfig/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/usr/local/lib/node_modules/kongfig/lib/kongState.js:21:191)
    at /usr/local/lib/node_modules/kongfig/lib/kongState.js:21:361
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)

Thanks.

**Comment by CyExy** [comment]
Just released a new `kongfig@1.5.0` you please try upgrading

**Comment by mburket** [comment]
hi, thanks for the quick turnaround. I installed the latest but still facing the same issue. 
TypeError: upstreams.map is not a function
 TypeError: upstreams.map is not a function
    at /usr/local/lib/node_modules/kongfig/lib/kongState.js:27:44
    at Generator.next (<anonymous>)
    at step (/usr/local/lib/node_modules/kongfig/lib/kongState.js:17:191)
    at /usr/local/lib/node_modules/kongfig/lib/kongState.js:17:361
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:169:7)

Here is my latest installed of kongfig
npm install kongfig -g
/usr/local/bin/kongfig -> /usr/local/lib/node_modules/kongfig/bin/kongfig
+ kongfig@1.5.0
removed 1 package and updated 2 packages in 3.22s

Thanks.

**Comment by CyExy** [comment]
It would be great to know what you get back from `/upstreams` with curl for example; is it actually the expected response, or a JSON error with `200 OK`. 

If it is correct do you have a next url in the response and does it look correct?
 
```bash
curl -k -i -X GET \
  -H "Accept: application/json" \
  -H "Authorization: Bearer jwt" \
  --url https://[admin-url]/upstreams
```

**Comment by mburket** [comment]
hi,
I executed the curl command as you suggested. I set up my admin apis as suggested by Kong: https://getkong.org/docs/0.12.x/secure-admin-api/#kong-api-loopback 

Thanks.

Here was my response:

HTTP/1.1 200 OK
Access-Control-Allow-Origin: *
Cache-control: no-cache="set-cookie"
Content-Type: application/json; charset=utf-8
Date: Wed, 28 Feb 2018 22:43:26 GMT
Server: kong/0.12.1
Via: kong/0.12.1
X-Kong-Proxy-Latency: 42
X-Kong-Upstream-Latency: 27
Content-Length: 21
Connection: keep-alive

{"data":{},"total":0}

**Comment by CyExy** [comment]
Thanks I now see what the problem is, will fix it tomorrow (GMT)

**Comment by CyExy** [comment]
So what I would expect to see is the following (notice the `"data":[]`)

```
HTTP/1.1 200 OK
Date: Thu, 01 Mar 2018 10:17:28 GMT
Content-Type: application/json; charset=utf-8
Transfer-Encoding: chunked
Connection: keep-alive
Access-Control-Allow-Origin: *
Server: kong/0.12.1

{"total":0,"data":[]}
```

`kongfig@1.5.1` should fix it for you. Please let me know if this fixes it for you if not please re-open the issue.

**Comment by mburket** [comment]
It works after the fix.  Thank you so much!

**Comment by CyExy** [comment]
No worries, let me know if you have any other issues.
