### ISSUE TITLE
Support for Health Check on Upstreams

### ISSUE THREAD

**Issue by lfventura** [mybuilder/kongfig#136]
Hello,

I have changed the code to add healthcheck support to upstreams, but I am not able to commit or create a new branch into this project. How should I do?

**Comment by alister** [comment]
Hi there. The best thing you can do is to make a fork of this repo, and do the work on the code updates a branch in your own space. From there, you can create a pull request where the developers of this project can look at it, and hopefully have it merged into the main project.

There are a few tutorials on how to do all that, such as https://help.github.com/articles/creating-a-pull-request-from-a-fork/ & https://gist.github.com/Chaser324/ce0505fbed06b947d962

**Comment by lfventura** [comment]
Thanks Alister.
Looking at it right now

**Comment by lfventura** [comment]
Thank you very much.
https://github.com/mybuilder/kongfig/pull/137
