### ISSUE TITLE
When adding a new plugin to an existent api it doesnt updates kong

### ISSUE THREAD

**Issue by lfventura** [mybuilder/kongfig#140]
Hello,

I have updated my original Kongfig .yml file adding a new plugin in an already existent API but it did not applied the new plugin to my API.

**Comment by CyExy** [comment]
Hi, could you please submit an example config file?

btw, check for yml file indentation issues, sometimes this can be the problem

**Comment by lfventura** [comment]
I think the problem is at Kong Enterprise itself... I tried via Curl and same thing happened.
I am investigating this further and I will keep you guys posted, but I think is a bug with my version.

I will close the issue for now as it doesnt looks related to kongfig.

**Comment by CyExy** [comment]
Sure no problem.
