### ISSUE TITLE
Idempotency and a "destroy" operation

### ISSUE THREAD

**Issue by jmdacruz** [mybuilder/kongfig#42]
I'm thinking about `konfig` as a tool similar to `terraform` or `ansible`, in the sense that you provide a description of what you want your environment to be, and the tool ensures that if the "apply" operation is successful you'll end up with the same configuration every time. In that sense, a "destroy" operation should do the exact oposite, that is, destroy the resources described on the config file.

Mapping this to `kongfig` seems to be straight forward, since a destroy operation should simply delete all the APIs listed on the config file. This is also related to the fact that `konfig` should (if it doesn't already) allow you to apply a config file multiple times, with the same result.

@CyExy: Do you think that contributing such an operation (destroy) is something doable for an outsider?

**Comment by CyExy** [comment]
You can apply a config file where `ensures` attribute is set to `removed` for an api or consumer, or any of their plugins, and it does exactly what it says on the tin.

`kongfig` allows for out of bounds apis and consumers, for example if you manage your consumers outside of kongfig, or when you would apply multiple config files to the same kong instance. The flip side is that you need to remember to remove old services with `ensure: removed` when you update your config file. If you are using puppet to configure our servers, then you would be doing the same in puppet as it requires this as well.

I can see how `destroy` operation could be useful in development, but I cannot think of a scenario where you would want to use it in production. Although having an option to remove any definitions from `Kong` that are not present in the config file would be probably welcomed options in some build systems.

**Comment by jmdacruz** [comment]
oh! cool... I missed that alternative. The `destroy` option would bring it closer to the behavior of terraform (not in production environments, but imagine a development or integration environment), but I think the `ensure: removed` keyword will do the trick for me. thanks!
