### ISSUE TITLE
Fatal Error when creating jwt for consumer. relation "jwt_secrets" does not exist.

### ISSUE THREAD

**Issue by vl4d** [mybuilder/kongfig#46]
Have consumer with jwt and run the apply command.
May have to do with there being a relational constraint in the db for jwt?
`
ERROR: relation "jwt_secrets" does not exist (22), client: 172.17.0.1, server: , request: "GET /consumers/vlad-test/jwt HTTP/1.1", host: "localhost:8001"
`

**Comment by gavinlove** [comment]
I am mostly sure this was a problem with kong and your database than kongfig. 

I think your migration hasn't happened.
