### ISSUE TITLE
Will Kongfig continue development after Kong 0.10 releases?

### ISSUE THREAD

**Issue by williamhorstkamp** [mybuilder/kongfig#55]
The next major version of Kong, `0.10` includes a CLI which provides a way to backup and apply configuration:
https://github.com/Mashape/kong/milestone/13

What are MyBuilder's plans in light of this? Are you planning to continue development, or re-evaluate the need after Kong 0.10 releases?

**Comment by CyExy** [comment]
I'm not sure that the Kong `backup/import` is meant for applying config written by hand. It looks more like a database dump, as it is just applied directly from/to DAO/schema, and it doesn't appear to go through any validation either.

**Comment by williamhorstkamp** [comment]
Excellent, I look forward to continuing to work with you guys then. 👍
