### ISSUE TITLE
Key-auth has to declare attributes.key

### ISSUE THREAD

**Issue by thenayr** [mybuilder/kongfig#57]
I'm wondering why Kongfig makes declaring the key non-optional. 

According to https://getkong.org/plugins/key-authentication/ , you should only be passing a pre-determined key if you are migrating from an existing API system,  otherwise kong itself will generate the key for you.

Is there a reason kongfig makes it a hard-dependency to pass a key attribute?

**Comment by cmikeb1** [comment]
+1, I'm also curious about this.

@CyExy, could you shed some light?

**Comment by CyExy** [comment]
To be able to declare consumer keys declaratively; the key acts as an ID, and it allows kongfig to look up existing keys and diff which ones needs to be added/removed. 

FIY any keys that are not found in the config file will be ignored; to revoke a key using kongfig you need to add `ensure: removed` to the key definition.

There are a few reasons for excluding consumers from kongfig. For example, you are adding and removing lots of consumers all the time. You can use `--ignore-consumers` option when using `apply` or `dump` to opt out.
