### ISSUE TITLE
I have a question about kongfig

### ISSUE THREAD

**Issue by oviwankenobi** [mybuilder/kongfig#58]
where I can send it to?

thanks

I have a kong installation already with Cassandra behind it; I need to export the current kong configuration to postgresql and move my current kong to postgresql; can kongfig help me out? 
I installed it on my kong server and I issued a command to export to yml and I got the following error

Error: http://kong:8001/consumers/raphi mapuser@mailmail.com/acls: 404 Not Found
 Error: http://kong:8001/consumers/raphi mapuser@mailmail.com/acls: 404 Not Found
    at /usr/local/lib/node_modules/kongfig/lib/adminApi.js:113:25
    at run (/usr/local/lib/node_modules/kongfig/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:87:22)
    at /usr/local/lib/node_modules/kongfig/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:100:28
    at flush (/usr/local/lib/node_modules/kongfig/node_modules/babel-polyfill/node_modules/core-js/modules/_microtask.js:18:9)
    at process._tickCallback (node.js:415:13)

**Comment by CyExy** [comment]
Hi, could you please send me what you get back from `http://kong:8001/plugins/enabled`

**Comment by oviwankenobi** [comment]
hi thanks for helping, here it is:
{
  "enabled_plugins": [
    "ssl",
    "jwt",
    "acl",
    "correlation-id",
    "cors",
    "oauth2",
    "tcp-log",
    "udp-log",
    "file-log",
    "http-log",
    "key-auth",
    "hmac-auth",
    "basic-auth",
    "ip-restriction",
    "galileo",
    "request-transformer",
    "response-transformer",
    "request-size-limiting",
    "rate-limiting",
    "response-ratelimiting",
    "syslog",
    "loggly",
    "datadog",
    "runscope",
    "ldap-auth",
    "statsd"
  ]
}

**Comment by CyExy** [comment]
Just published `kongfig@1.2.23` that should fix your issue. This is actually Kong admin API issue where it doesn't like spaces in usernames.

**Comment by oviwankenobi** [comment]
sweet! you are a life savior, thank you @CyExy

**Comment by CyExy** [comment]
Your welcome, and thanks for reporting!

**Comment by oviwankenobi** [comment]
I have just reported another one
https://github.com/mybuilder/kongfig/issues/59
not as urgent as this one though :)
