### ISSUE TITLE
error when apply is called second time if it was interrupted initially

### ISSUE THREAD

**Issue by oviwankenobi** [mybuilder/kongfig#59]
I issued an apply and it was interrupted cause I forgot to issue it in background and my session died.
when I re-issued the same command it failed -- see the error below;
background: the configuration has a lot of consumers, all the config settings were applied when the first apply was running except the creation of consumers; so when I re-issued the command I expected either to fail when trying to re-create an already existing consumer or just skip the consumer if it was already created; in the error I see it is not able to handle the acl groups...? anyway, maybe it is a known issue, I think it would be nice to be fixed. thank you!

POST 400 http://kong:8001/consumers/2b5fff0a-dd19-1d35-a2e1-0a228e4959ec/acls
 { group: 'GROUP_NAME'}
Error: Bad Request
{"group":"ACL group already exist for this consumer"}

 Error: Bad Request
{"group":"ACL group already exist for this consumer"}

    at /usr/local/lib/node_modules/kongfig/lib/core.js:152:43
    at run (/usr/local/lib/node_modules/kongfig/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:87:22)
    at /usr/local/lib/node_modules/kongfig/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:100:28
    at flush (/usr/local/lib/node_modules/kongfig/node_modules/babel-polyfill/node_modules/core-js/modules/_microtask.js:18:9)
    at process._tickCallback (node.js:415:13)

**Comment by CyExy** [comment]
I have an idea what could be the issue, let me have a look.

**Comment by CyExy** [comment]
`kongfig@1.2.24` fixes this issue, thanks!
