### ISSUE TITLE
kongfig export is not exporting custom_id for consumers

### ISSUE THREAD

**Issue by oviwankenobi** [mybuilder/kongfig#60]
I have lost of consumers in configuration (>1000) 
when I export to config.yml and the import it I do not have consumer custom_id (because the produced config.yml is not having it);
can you please fix this, it is very important for us, without the custom_id we can not authenticate the users on the upstream side. we are moving away from Cassandra and need to export from Cassandra and import in PostgreSQL.
thank you!

**Comment by CyExy** [comment]
Thanks for reporting, `kongfig@1.2.25` fixes it.

**Comment by oviwankenobi** [comment]
thank you!

**Comment by oviwankenobi** [comment]
hnmmm I have spoken too soon, after installing this last version simple dump fails 

Error: http://kong:8001/consumers/db703237-ba08-43b0-84a5-d40b17d083b2/acls: 500 Internal Server Error
 Error: http://kong:8001/consumers/db703237-ba08-43b0-84a5-d40b17d083b2/acls: 500 Internal Server Error
    at /usr/lib/node_modules/kongfig/lib/adminApi.js:113:25
    at run (/usr/lib/node_modules/kongfig/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js$
    at /usr/lib/node_modules/kongfig/node_modules/babel-polyfill/node_modules/core-js/modules/es6.promise.js:100:$
    at flush (/usr/lib/node_modules/kongfig/node_modules/babel-polyfill/node_modules/core-js/modules/_microtask.j$
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)

**Comment by oviwankenobi** [comment]
more info: this error it seems it is not related with latest version, I have installed the previous kongfig@1.2.24 version and it still repro-ing; that is weird. I am on a different machine now, that's the only difference; should I create a new issue?

**Comment by CyExy** [comment]
Getting a 500 error is odd, I think you are hitting a connection or rate limit with nginx. What do you get in Kong logs?

**Comment by oviwankenobi** [comment]
hmmm indeed in /usr/local/kong/logs/error.log I get

2017/01/13 06:53:41 [error] 32690#0: *502 [lua] responses.lua:99: handler(): FATAL: sorry, too many clients already, client: 127.0.0.1, server: , request: "GET /consumers/fc5d6413-bfa6-47eb-829d-da09372ab146/oauth2 HTTP/1.1", host: "kong:8001"

but why is that? is the tool spawning multiple connections in the same time?... how can I tune this so it will work? I have restarted the kong and PostgreSQL and I get this error right away not after some time... there's no external callers at this time since the server is out of rotation.

**Comment by gavinlove** [comment]
That is a postgres error, the quickest solution would be to increase the max number of postgres connections. What is your max kong connections? your postgres limit needs to be at that number plus 5 really as a minimum.

**Comment by oviwankenobi** [comment]
postgres connection limit is 100
kong connections limit? ... I can't find where I an set that.
but how come instantly after I run the apply or dump it fails with this error? after I restarted postgres and kong and I know there's nobody hitting this server?

**Comment by gavinlove** [comment]
You should look at this document, kong uses nginx as its platform. https://www.nginx.com/blog/tuning-nginx/

**Comment by fplotnikov** [comment]
Hi
When we set postgre connections limit from 100 to 500 and start kongfig to migrate data system spawn 400 connections with 400 postgre  childs. System became very slow. 

Is it normal? :)

**Comment by oviwankenobi** [comment]
hmmm, I raised the postgres connection limit to 500 and it seems it is running but what I also observed is that it spawned 400 concurent connections. that is not right. why kongfig is doing this?

**Comment by viveknimkarde** [comment]
Did anyone find solution yet ?
