### ISSUE TITLE
500 Internal Server Error if more than 21 api end points set

### ISSUE THREAD

**Issue by quanghiem** [mybuilder/kongfig#61]
Hi, 

I'm having a weird problem where I'm getting an `500 Internal Server Error` error when I try to add the 22nd api end point using Kongfig.  

```
POST 201 http://localhost:8001/apis
 { request_path: '/api21',
  strip_request_path: true,
  preserve_host: false,
  upstream_url: 'https://api21',
  name: 'api21' }
Response status Created:
 { upstream_url: 'https://api21',
  request_path: '/api21',
  id: 'fffbbd2f-c5ed-4e7b-b7c9-d8e1995faaf4',
  created_at: 1487245975000,
  preserve_host: false,
  strip_request_path: true,
  name: 'api21' }

POST 201 http://localhost:8001/apis
 { request_path: '/api22',
  strip_request_path: true,
  preserve_host: false,
  upstream_url: 'https://api22',
  name: 'api22' }
Response status Created:
 { upstream_url: 'https://api22',
  request_path: '/api22',
  id: '4481de66-f0f8-486d-9e17-b1f5593f87a9',
  created_at: 1487245975000,
  preserve_host: false,
  strip_request_path: true,
  name: 'api22' }
Error: http://localhost:8001/apis/fffbbd2f-c5ed-4e7b-b7c9-d8e1995faaf4/plugins: 500 Internal Server Error
 Error: http://localhost:8001/apis/fffbbd2f-c5ed-4e7b-b7c9-d8e1995faaf4/plugins: 500 Internal Server Error
    at /usr/local/node/node-v6.7.0/lib/node_modules/kongfig/lib/adminApi.js:113:25
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

Here is the curl of the error URL:

```
$ curl -s http://localhost:8001/apis/fffbbd2f-c5ed-4e7b-b7c9-d8e1995faaf4/plugins | jq .
{
  "total": 0,
  "data": []
}
```

After the 500 error occurs, all Kongfig apply and other commands throw the same 500 error:

```
$ /usr/local/node/node-v6.7.0/bin/kongfig dump
Error: http://localhost:8001/apis/fffbbd2f-c5ed-4e7b-b7c9-d8e1995faaf4/plugins: 500 Internal Server Error
 Error: http://localhost:8001/apis/fffbbd2f-c5ed-4e7b-b7c9-d8e1995faaf4/plugins: 500 Internal Server Error
    at /usr/local/node/node-v6.7.0/lib/node_modules/kongfig/lib/adminApi.js:113:25
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

Regular curl commands to localhost:8001 and localhost:8001/plugins work fine.

My setup is running the latest Kong version 0.9.9 and latest Kongfig version 1.2.25.  I have 24 apis and 1 consumer.  I got the 500 error when running my entire config yaml file.  As I started removing apis to pin point if one was bad, I noticed that the error was thrown only when I tried to add the 22nd api.  In between applies, I was wiping all existing apis with `ensure: "removed"` to simulate a fresh apply.

Any help would be much appreciated.

Richard

**Comment by quanghiem** [comment]
Found the problem.  It was my AWS RDS PSQL DB instance size of t2.micro.  That only allows 26 max connections, minus 3 reserved for the super user.

**Comment by CyExy** [comment]
Still a bit odd, this might be related to another issue people have been reporting where kongfig is using too many connections.

**Comment by hiephm** [comment]
I just encountered this issue (I'm using Cassandra) and here the way for quick fix:
vim /usr/lib/node_modules/kongfig/lib/router.js
Search this lines:
```
            case 'consumers':
                return adminApiRoot + '/consumers';
```
and change it to 
```
            case 'consumers':
                return adminApiRoot + '/consumers?size=20';
```
to limit consumers returned in each page, hence limit the connections
