### ISSUE TITLE
Kong 0.10 API format changes

### ISSUE THREAD

**Issue by c-knowles** [mybuilder/kongfig#63]
I thought worth creating a placeholder for the Kong 0.10 API format changes. Release notes are on https://github.com/Mashape/kong/releases but there are also a few changes to the API not explicitly listed.

So far I found the `apis` endpoint changes:
1. `request_host` -> `hosts`
1. `request_path` -> `uris`
1. `strip_request_path` -> `strip_uri`
1. Adds `retries`, `upstream_connect_timeout`, `upstream_read_timeout` and `upstream_send_timeout`

#### 0.9.9
```
✗ curl -s http://localhost:8001/apis | jq
{
  "data": [
    {
      "created_at": 1488523764000,
      "id": "38a544a4-e190-46dc-86b5-09d9c54ab7b0",
      "name": "mockbin",
      "preserve_host": false,
      "request_host": "mockbin.com"
      "request_path": "/mockbin",
      "strip_request_path": true,
      "upstream_url": "http://mockbin.com/",
    }
  ],
  "total": 1
}
```

#### 0.10 RC4
```
✗ curl -s http://localhost:8001/apis | jq
{
  "data": [
    {
      "created_at": 1488523764000,
      "hosts": [
        "mockbin.com"
      ],
      "id": "38a544a4-e190-46dc-86b5-09d9c54ab7b0",
      "name": "mockbin",
      "preserve_host": false,
      "retries": 5,
      "strip_uri": true,
      "upstream_connect_timeout": 60000,
      "upstream_read_timeout": 60000,
      "upstream_send_timeout": 60000,
      "upstream_url": "http://mockbin.com",
      "uris": [
        "/mockbin"
      ]
    }
  ],
  "total": 1
}
```

**Comment by CyExy** [comment]
Is the API schema change going to be a PC break?

**Comment by CyExy** [comment]
Hmm.., the release doc actually says that it is not going to support the old format. So not sure can we maintain backwards compatibility or not.

**Comment by c-knowles** [comment]
From the looks of things yes there's little in the way of compatibility. There could be some ways to maintain some basic compatibility in kongfig. For example if `uris` is one in length pass it through on the old format if we can detect the version. However, I think users can easily upgrade if instructions are provided. e.g. 1) upgrade kong, 2) take an export with a newer kongfig version.

**Comment by Tombar** [comment]
Hello, any news about adding support for KONG v0.10?

**Comment by rogoman** [comment]
A proposed fix for this: https://github.com/mybuilder/kongfig/pull/64

**Comment by CyExy** [comment]
I think we need to support applying pre 10 kongfig files to kong 10. #64 deals with the dumping so I'll try to fix the `apply` side.
