### ISSUE TITLE
Anonymous setting in Auth Plugins

### ISSUE THREAD

**Issue by adamlc** [mybuilder/kongfig#65]
The anonymous setting in auth plugins is a Consumer UUID, which get exported correctly, but obviously when kongfig imports it again the UUID is different from the one specified.

Is there a way kongfig could keep a reference to which consumer the key is for so it that can be recreated accurately afterwards with the new UUID?

**Comment by CyExy** [comment]
Should allow `config.anonymous.custom_id` or `config.anonymous.username` instead of customer id.

**Comment by Gui13** [comment]
This won't work since the anonymous is supposed to be the actual UUID of the anonymous user:

> An optional string (consumer uuid) value to use as an “anonymous” consumer if authentication fails. If empty (default), the request will fail with an authentication failure 4xx. Please note that this value must refer to the Consumer id attribute which is internal to Kong, and not its custom_id.

https://docs.konghq.com/hub/kong-inc/basic-auth/
