### ISSUE TITLE
Support for certificates and SNI

### ISSUE THREAD

**Issue by bspaans** [mybuilder/kongfig#73]
Hi and thanks for a great tool! 

As of 0.10 the SSL plugin is no longer included with Kong and I was just wondering if you'll be supporting the new certificate and SNI management endpoints?

**Comment by CyExy** [comment]
Thanks for submitting the issue. Supporting Certificate & SNI is a no-brainer.

**Comment by jonathan-kosgei** [comment]
@CyExy Any progress on this?

**Comment by CyExy** [comment]
Sorry, have been busy with other stuff, hope to get some time to work on it.

**Comment by CyExy** [comment]
@jonathan-kosgei @bspaans Added a PR for this it would be great if you find time to check it out #102 thanks.
