### ISSUE TITLE
kongfig apply

### ISSUE THREAD

**Issue by mrafieee** [mybuilder/kongfig#84]
kongfig apply does not sync with the dump file, if some endpoints get removed it does not reflect via apply command,

how can I delete endpoints from dump config and apply it?

**Comment by CyExy** [comment]
kongfig follows a similar declarative configuration as Puppet where you need to explicitly declare what needs to be removed. This is because you might apply multiple configurations files, or choose to handle consumers outside kongfig.

For example, to remove an API you can use `ensure: "removed"`

```
apis:
  - name: mockbin # unique api name
    ensure: "removed"
```
